using System;
using System.Collections.Generic;

namespace task1
{

    class Program
    {
        static List<string> FrequentWords(string s, int k)
        {
            Dictionary<string, int> cnt = new Dictionary<string, int>();
            List<string> ans = new List<string>();
            int m = 0;
            for (int i = 0; i < s.Length - k; i++)
            {
                var sub = s.Substring(i, k);
                if (!cnt.ContainsKey(sub))
                    cnt.Add(sub, 0);
                cnt[sub]++;
                m = Math.Max(m, cnt[sub]);
            }
            foreach (var key in cnt.Keys)
            {
                if (cnt[key] == m)
                    ans.Add(key);
            }
            return ans;
        }

        static void Main(string[] args)
        {
            foreach (var word in FrequentWords("CCAGTACATGCCAGTACATGTGCGAGGGATTGGTCCTGTATAGAGAACAGACAAGTATAGAGTTGGTCCTAACAGACAATTGGTCCTGTATAGAGAACAGACAAGTATAGAGCCAGTACATGAACAGACAATTGGTCCTGTATAGAGCCAGTACATGAACAGACAACCAGTACATGCCAGTACATGTTGGTCCTTGCGAGGGATTGGTCCTTTGGTCCTTGCGAGGGACCAGTACATGGTATAGAGTTGGTCCTTTGGTCCTTGCGAGGGACCAGTACATGAACAGACAACCAGTACATGCCAGTACATGTTGGTCCTTTGGTCCTCCAGTACATGAACAGACAATGCGAGGGAAACAGACAAGTATAGAGTGCGAGGGATGCGAGGGATTGGTCCTAACAGACAATGCGAGGGAGTATAGAGCCAGTACATGTTGGTCCTTGCGAGGGATGCGAGGGAGTATAGAGAACAGACAAAACAGACAATTGGTCCTTTGGTCCTTTGGTCCTGTATAGAGTTGGTCCTAACAGACAAGTATAGAGTGCGAGGGATTGGTCCTCCAGTACATGTTGGTCCTAACAGACAAGTATAGAGAACAGACAAGTATAGAGGTATAGAGGTATAGAGAACAGACAATGCGAGGGACCAGTACATGGTATAGAGCCAGTACATGAACAGACAAGTATAGAGGTATAGAGGTATAGAGTGCGAGGGATTGGTCCTTGCGAGGGAGTATAGAGCCAGTACATGCCAGTACATGGTATAGAGTTGGTCCTGTATAGAGAACAGACAAGTATAGAGTGCGAGGGACCAGTACATGTTGGTCCTAACAGACAAAACAGACAACCAGTACATGTTGGTCCTCCAGTACATGAACAGACAAGTATAGAGTTGGTCCTTGCGAGGGATTGGTCCTAACAGACAACCAGTACATGTTGGTCCTGTATAGAGTTGGTCCTCCAGTACATG", 12))
                Console.WriteLine(word);
        }
    }
}